const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const KEY="planejaedu_data_v4", PIX="49 99967-4823";
const defaultData={user:null,theme:"light",headers:[
{name:"Escola Municipal Professora Irmã Blandina Cisz",desc:"Município de Lajeado Grande",type:"Escola municipal"},
{name:"Escola Estadual",desc:"Rede estadual de ensino",type:"Escola estadual"},
{name:"Escola Particular",desc:"Instituição particular",type:"Escola particular"},
{name:"Irmã Blandina",desc:"Secretaria Municipal de Educação",type:"Secretaria"},
{name:"Integral (Lajeado Grande)",desc:"Cabeçalho de projeto",type:"Integral"}
],classes:[],students:[],materials:[]};
let data=JSON.parse(localStorage.getItem(KEY)||"null")||defaultData;
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function show(id){$$(".screen").forEach(x=>x.classList.add("hidden"));$("#"+id).classList.remove("hidden")}
function toast(t){const x=$("#toast");x.textContent=t;x.style.display="block";setTimeout(()=>x.style.display="none",2600)}
function pixModal(){ $("#pix-modal").classList.remove("hidden") }
function start(){pixModal();show("login")}
function login(){show("login")}
function enter(name="Professora"){data.user=name;save();$("#user-name").textContent=name;$("#avatar").textContent=name[0].toUpperCase();show("app-screen");render("home")}
function pageHead(k,s,b=""){return `<div class="page-head"><div><div class="eyebrow">PLANEJAMENTO ESCOLAR</div><h1>${k}</h1><p class="sub">${s}</p></div>${b}</div>`}
function render(p){
  $$(".nav").forEach(n=>n.classList.toggle("active",n.dataset.page===p));
  let html="";
  if(p==="home") html=pageHead("Visão geral","Seu espaço pedagógico gratuito.")+`<div class="cards">
  <div class="stat"><small>Turmas</small><br><b>${data.classes.length}</b></div><div class="stat"><small>Alunos</small><br><b>${data.students.length}</b></div>
  <div class="stat"><small>Materiais salvos</small><br><b>${data.materials.length}</b></div><div class="stat"><small>Professores ativos</small><br><b>1</b></div></div>
  <div class="panel"><h2>Comece agora</h2><div class="tool-picker">${["Plano de aula","Slides","Prova e avaliação","Lista de exercícios","Mapa mental","Jogos educativos","Projeto","Adaptação","Comunicação","Ideias de atividades","Resumo","Assistente IA"].map((x,i)=>`<button class="tool-btn" onclick="openGenerator('${x}')"><i class="icon icon-sparkles"></i> ${x}</button>`).join("")}</div></div>`;
  if(p==="planner") html=generator();
  if(p==="classes") html=classesPage();
  if(p==="students") html=studentsPage();
  if(p==="attendance") html=attendancePage();
  if(p==="calendar") html=calendarPage();
  if(p==="headers") html=headersPage();
  if(p==="library") html=libraryPage();
  if(p==="settings") html=settingsPage();
  $("#page").innerHTML=`<div class="page">${html}</div>`;
}
function generator(){
return pageHead("Criar material","Planeje aulas, atividades e avaliações com um gerador pedagógico local.")+
`<div class="panel"><div class="field"><label>Tipo de material</label><select id="gen-type">${["Plano de aula","Slides","Prova e avaliação","Lista de exercícios","Mapa mental","Jogos educativos","Projeto","Adaptação","Comunicação","Ideias de atividades","Resumo","Assistente IA"].map(x=>`<option>${x}</option>`).join("")}</select></div>
<div class="grid2"><div class="field"><label>Ano/série</label><input id="gen-grade" placeholder="Ex.: 4º ano"></div><div class="field"><label>Disciplina</label><input id="gen-subject" placeholder="Ex.: Ciências"></div></div>
<div class="field"><label>O que deseja preparar?</label><textarea id="gen-prompt" rows="5" placeholder="Descreva o tema, objetivo, duração, perfil da turma e o que gostaria de incluir..."></textarea></div>
<div class="grid2"><div class="field"><label>Cabeçalho</label><select id="gen-header">${data.headers.map((h,i)=>`<option value="${i}">${h.name}</option>`).join("")}</select></div><div class="field"><label>Turno</label><select id="gen-shift"><option>Matutino</option><option>Vespertino</option><option>Noturno</option><option>Integral</option></select></div></div>
<button class="primary" onclick="generateLocal()"><i class="icon icon-sparkles"></i> Gerar material</button></div>
<div id="gen-output"></div>`;
}
function openGenerator(t){render("planner");setTimeout(()=>$("#gen-type").value=t,0)}
function generateLocal(){
 const type=$("#gen-type").value,grade=$("#gen-grade").value||"turma",sub=$("#gen-subject").value||"a disciplina",prompt=$("#gen-prompt").value||"o tema indicado";
 const h=data.headers[Number($("#gen-header").value)]?.name||"PlanejaEdu";
 const shift=$("#gen-shift").value;
 const material=buildMaterial(type,grade,sub,prompt,shift,h);
 data.materials.push({type,date:new Date().toLocaleDateString("pt-BR"),title:prompt,content:material});save();
 $("#gen-output").innerHTML=`<div class="panel"><div class="result-head"><div><div class="eyebrow">MATERIAL GERADO</div><h2>${esc(type)}</h2></div><button class="ghost" onclick="copyText(${JSON.stringify(material)})"><i class="icon icon-copy"></i> Copiar</button></div><div class="output">${esc(material)}</div></div>`;
}
function buildMaterial(type,grade,sub,prompt,shift,h){
 const common=`Cabeçalho: ${h}\nAno/série: ${grade}\nDisciplina: ${sub}\nTurno: ${shift}\nTema: ${prompt}`;
 const intro=`A proposta foi estruturada para ${grade}, considerando linguagem adequada à faixa etária, participação ativa e relação com conhecimentos prévios.`;
 if(type==="Plano de aula") return `${h}\n\nPLANO DE AULA\n\n${common}\n\nOBJETIVOS DE APRENDIZAGEM\n• Compreender os conceitos centrais de ${prompt}.\n• Relacionar o conteúdo a situações do cotidiano.\n• Desenvolver participação, argumentação e registro.\n\nDURAÇÃO SUGERIDA\n50 a 100 minutos, podendo ser adaptada ao horário da turma.\n\nACOLHIDA E CONHECIMENTOS PRÉVIOS\nInicie com perguntas disparadoras sobre ${prompt}. Registre as hipóteses dos estudantes e retome conhecimentos já trabalhados.\n\nDESENVOLVIMENTO\n1. Apresente o problema ou situação motivadora.\n2. Faça uma explicação dialogada, usando exemplos concretos.\n3. Proponha atividade individual ou colaborativa.\n4. Faça a socialização e sistematize as conclusões.\n\nATIVIDADE PRÁTICA\nCrie uma tarefa em que os estudantes precisem observar, resolver, produzir ou explicar algo relacionado a ${prompt}.\n\nAVALIAÇÃO\nObserve participação, compreensão, estratégias utilizadas, registros e capacidade de explicar o que aprendeu.\n\nADAPTAÇÕES\nOfereça instruções em etapas, exemplos visuais, tempo adicional quando necessário e diferentes formas de registro.\n\nRECURSOS\nQuadro, folhas, lápis, materiais concretos e recursos digitais disponíveis.`;
 if(type==="Prova e avaliação") return `${h}\n\nAVALIAÇÃO\n\n${common}\n\nORIENTAÇÕES\n${intro}\n\nQUESTÕES\n1. Questão objetiva sobre ${prompt}.\n2. Questão de associação ou classificação.\n3. Questão de resposta curta com justificativa.\n4. Situação-problema contextualizada.\n5. Questão de aplicação do conteúdo em uma situação cotidiana.\n\nGABARITO\n1. Resposta coerente com o conceito central trabalhado.\n2. Associação/classificação conforme o conteúdo desenvolvido.\n3. Deve apresentar ideia principal e justificativa.\n4. Valorize estratégia e raciocínio, além do resultado.\n5. Considere aplicação correta do conceito.\n\nCRITÉRIOS\nCompreensão, aplicação, clareza do registro, autonomia e participação.`;
 if(type==="Lista de exercícios") return `${h}\n\nLISTA DE EXERCÍCIOS\n\n${common}\n\n${intro}\n\n1. Retome o conceito de ${prompt} com suas próprias palavras.\n2. Resolva uma situação simples relacionada ao tema.\n3. Compare dois exemplos e explique a diferença.\n4. Resolva uma situação-problema contextualizada.\n5. Crie um exemplo próprio sobre ${prompt}.\n6. Desafio: explique como você ensinaria esse conteúdo a um colega.\n\nGABARITO ORIENTADOR\nAs respostas devem demonstrar compreensão do conceito, uso adequado da estratégia e justificativa.`;
 if(type==="Slides") return `${h}\n\nROTEIRO DE SLIDES\n\n${common}\n\nSLIDE 1 — TÍTULO\n${prompt}\n\nSLIDE 2 — OBJETIVOS\nO que vamos aprender e por que esse conhecimento é importante.\n\nSLIDE 3 — ATIVAÇÃO\nPergunta ou imagem para levantar conhecimentos prévios.\n\nSLIDE 4 — CONCEITO PRINCIPAL\nExplicação curta com exemplos.\n\nSLIDE 5 — EXEMPLO\nSituação prática relacionada ao cotidiano.\n\nSLIDE 6 — DESAFIO\nPergunta para a turma resolver em duplas ou grupos.\n\nSLIDE 7 — SISTEMATIZAÇÃO\nResumo visual dos pontos principais.\n\nSLIDE 8 — AVALIAÇÃO\nPergunta de saída para verificar a aprendizagem.`;
 if(type==="Mapa mental") return `${h}\n\nMAPA MENTAL\n\nCENTRO: ${prompt}\n\nCONCEITO PRINCIPAL\n→ definição\n→ características\n→ exemplos\n\nAPLICAÇÃO\n→ situações do cotidiano\n→ problemas que podem ser resolvidos\n\nVOCABULÁRIO\n→ palavras-chave do conteúdo\n\nSÍNTESE\n→ o que o estudante precisa lembrar ao final.`;
 if(type==="Resumo") return `${h}\n\nRESUMO DIDÁTICO\n\n${common}\n\nIDEIA CENTRAL\n${prompt} é o eixo do estudo desta proposta.\n\nPONTOS-CHAVE\n• Conceitos essenciais.\n• Características e relações.\n• Exemplos de aplicação.\n• Vocabulário importante.\n\nPARA REVISAR\nPeça ao estudante que explique o conteúdo sem consultar o material e depois compare com os pontos-chave.`;
 if(type==="Jogos educativos") return `${h}\n\nJOGO EDUCATIVO\n\n${common}\n\nNOME DO JOGO\nDesafio ${prompt}\n\nOBJETIVO\nReforçar ${prompt} de maneira lúdica e colaborativa.\n\nCOMO JOGAR\n1. Divida a turma em equipes ou duplas.\n2. Apresente desafios graduados.\n3. Dê pontos por resposta correta e por justificativa.\n4. Inclua uma rodada final de desafio.\n\nVARIAÇÕES\nUse cartas, quadro, dados, perguntas orais ou versão digital.`;
 return `${h}\n\n${type.toUpperCase()}\n\n${common}\n\nPROPOSTA\n${intro}\n\nETAPA 1 — PREPARAÇÃO\nDefina o objetivo principal e os conhecimentos prévios necessários.\n\nETAPA 2 — DESENVOLVIMENTO\nOrganize uma atividade ativa, contextualizada e adequada ao nível da turma.\n\nETAPA 3 — PRODUÇÃO\nPeça um registro, produto, apresentação ou resolução relacionada a ${prompt}.\n\nETAPA 4 — AVALIAÇÃO\nObserve evidências de aprendizagem e registre avanços e dificuldades.\n\nINCLUSÃO\nDisponibilize diferentes formas de participação e registro.`;
}
function esc(s){return s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function copyText(t){navigator.clipboard?.writeText(t);toast("Copiado!")}
function classesPage(){return pageHead("Turmas","Cadastre turmas, turno e vincule alunos.",`<button class="primary" onclick="addClass()">+ Nova turma</button>`)+`<div class="panel"><div class="list">${data.classes.length?data.classes.map((c,i)=>`<div class="row"><div><b>${c.name}</b><small class="sub"><br>${c.segment} • ${c.shift} • ${c.school||"Escola não definida"}</small></div><span class="pill">${data.students.filter(s=>s.classId===i).length} alunos</span></div>`).join(""):`<p class="sub">Nenhuma turma cadastrada ainda.</p>`}</div></div>`}
function addClass(){const n=prompt("Nome da turma (ex.: 4º ano A):");if(!n)return;const seg=prompt("Segmento (Educação Infantil, Ensino Fundamental ou Ensino Médio):","Ensino Fundamental");const shift=prompt("Turno:","Matutino");const school=prompt("Escola:","Escola Municipal");data.classes.push({name:n,segment:seg,shift,school});save();render("classes");toast("Turma adicionada")}
function studentsPage(){return pageHead("Alunos","Cadastre os estudantes para usar a chamada automática.",`<button class="primary" onclick="addStudent()">+ Novo aluno</button>`)+`<div class="panel"><div class="list">${data.students.length?data.students.map(s=>`<div class="row"><div><b>${s.name}</b><small class="sub"><br>${data.classes[s.classId]?.name||"Turma não encontrada"}</small></div><i class="icon icon-user-round"></i></div>`).join(""):`<p class="sub">Cadastre os alunos individualmente ou use a opção de enviar uma lista pelo WhatsApp.</p>`}</div></div>`}
function addStudent(){if(!data.classes.length){toast("Crie uma turma primeiro.");return}const n=prompt("Nome completo do aluno:");if(!n)return;const opts=data.classes.map((c,i)=>`${i}: ${c.name}`).join("\\n");const id=Number(prompt("Digite o número da turma:\\n"+opts,"0"));data.students.push({name:n,classId:isNaN(id)?0:id});save();render("students")}
function attendancePage(){return pageHead("Chamada automática","A lista é montada a partir dos alunos cadastrados.")+`<div class="panel"><div class="field"><label>Turma</label><select id="att-class" onchange="renderAttendance()">${data.classes.map((c,i)=>`<option value="${i}">${c.name} — ${c.shift}</option>`).join("")}</select></div><div id="att-list"></div></div>`}
function renderAttendance(){const id=Number($("#att-class").value);const st=data.students.filter(s=>s.classId===id);$("#att-list").innerHTML=st.length?`<div class="list">${st.map(s=>`<label class="check"><input type="checkbox" checked> ${s.name}</label>`).join("")}</div><br><button class="primary" onclick="toast('Chamada salva localmente!')">Salvar chamada</button>`:`<p class="sub">Não há alunos nesta turma. Cadastre os nomes na aba Alunos.</p>`}
function calendarPage(){
 const now=new Date(), ym=calendarState.ym||`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;
 const [y,m]=ym.split("-").map(Number);
 return pageHead("Calendário","Monte e altere sua rotina do jeito que preferir.",`<div class="calendar-actions"><button class="ghost" onclick="changeMonth(-1)"><i class="icon icon-chevron-left"></i></button><b>${new Date(y,m-1,1).toLocaleDateString("pt-BR",{month:"long",year:"numeric"})}</b><button class="ghost" onclick="changeMonth(1)"><i class="icon icon-chevron-right"></i></button><button class="primary" onclick="openEventForm()">+ Novo evento</button></div>`)+
 `<div class="panel calendar-panel"><div class="calendar-week">${["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"].map(d=>`<div>${d}</div>`).join("")}</div><div class="calendar-grid">${calendarCells(y,m)}</div></div><div class="panel"><h2>Próximos eventos</h2><div id="event-list">${eventList()}</div></div>`;
}
let calendarState={ym:null};
function calendarCells(y,m){const first=new Date(y,m-1,1).getDay(),days=new Date(y,m,0).getDate(),cells=[];for(let i=0;i<first;i++)cells.push(`<div class="day empty"></div>`);for(let d=1;d<=days;d++){const iso=`${y}-${String(m).padStart(2,"0")}-${String(d).padStart(2,"0")}`;const ev=events().filter(e=>e.d===iso);cells.push(`<div class="day" onclick="openEventForm('${iso}')"><div class="day-num">${d}</div>${ev.map(e=>`<button class="event-chip" onclick="event.stopPropagation();editEvent('${e.id}')">${esc(e.n)}</button>`).join("")}<button class="day-add" onclick="event.stopPropagation();openEventForm('${iso}')">+</button></div>`)}return cells.join("")}
function events(){return JSON.parse(localStorage.getItem("pe_events")||"[]")}
function saveEvents(a){localStorage.setItem("pe_events",JSON.stringify(a));}
function changeMonth(delta){const [y,m]=(calendarState.ym||`${new Date().getFullYear()}-${String(new Date().getMonth()+1).padStart(2,"0")}`).split("-").map(Number);const d=new Date(y,m-1+delta,1);calendarState.ym=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`;render("calendar")}
function openEventForm(date=""){const name=prompt("Nome da aula, avaliação ou evento:","");if(!name)return;const d=date||prompt("Data (AAAA-MM-DD):",new Date().toISOString().slice(0,10));if(!d)return;const shift=prompt("Turno:","Matutino");const arr=events();arr.push({id:Date.now().toString(),d,n:name,shift:shift||"Matutino"});saveEvents(arr);render("calendar");toast("Evento adicionado")}
function editEvent(id){const arr=events(),e=arr.find(x=>x.id===id);if(!e)return;const action=prompt(`Editar evento:\n\n${e.n}\n${e.d}\n\nDigite: 1 para renomear, 2 para mudar data, 3 para excluir`,`1`);if(action==="1"){const n=prompt("Novo nome:",e.n);if(n)e.n=n}else if(action==="2"){const d=prompt("Nova data (AAAA-MM-DD):",e.d);if(d)e.d=d}else if(action==="3"){if(!confirm("Excluir este evento?"))return;arr.splice(arr.indexOf(e),1)}saveEvents(arr);render("calendar");toast("Calendário atualizado")}
function eventList(){const a=events().sort((x,y)=>x.d.localeCompare(y.d));return a.length?`<div class="list">${a.map(e=>`<div class="row"><div><b>${esc(e.n)}</b><small class="sub"><br>${new Date(e.d+"T12:00").toLocaleDateString("pt-BR")} • ${esc(e.shift||"Matutino")}</small></div><button class="ghost" onclick="editEvent('${e.id}')">Editar</button></div>`).join("")}</div>`:`<p class="sub">Seu calendário está livre. Clique em um dia ou em “Novo evento” para começar.</p>`}
function headersPage(){return pageHead("Cabeçalhos","Escolha um ou mais cabeçalhos para seus planos.")+`<div class="panel"><p class="sub">Você pode marcar vários. O cabeçalho escolhido aparece no material gerado.</p>${data.headers.map((h,i)=>`<label class="header-card"><span><b>${h.name}</b><small class="sub"><br>${h.desc}</small></span><input type="checkbox" ${i===0?"checked":""} onchange="toast(this.checked?'Cabeçalho selecionado':'Cabeçalho retirado')"></label>`).join("")}</div>`}
function libraryPage(){return pageHead("Biblioteca","Materiais criados neste dispositivo.")+`<div class="panel"><div class="list">${data.materials.length?data.materials.slice().reverse().map(m=>`<div class="row"><div><b>${m.title}</b><small class="sub"><br>${m.type} • ${m.date}</small></div><button class="ghost" onclick="openGenerator('${m.type}')">Abrir</button></div>`).join(""):`<p class="sub">Sua biblioteca está vazia.</p>`}</div></div>`}
function settingsPage(){return pageHead("Configurações","Personalize seu espaço pedagógico.")+`<div class="panel"><h2>Perfil</h2><div class="grid2"><div class="field"><label>Nome</label><input id="set-name" value="${esc(data.user||"Professora")}"></div><div class="field"><label>Foto</label><input id="set-photo" type="file" accept="image/*" onchange="photoPreview(this)"></div></div><button class="primary" onclick="saveSettings()">Salvar perfil</button></div><div class="panel"><h2>Aparência</h2><p class="sub">Modo escuro para usar o site com mais conforto.</p><button class="primary" onclick="toggleTheme()">Alternar modo escuro</button></div><div class="panel"><h2>Contribuição</h2><p class="sub">O projeto não tem plano pago. Se quiser contribuir, use o Pix da criadora.</p><button class="primary" onclick="pixModal()">Ver Pix</button></div>`}
function saveSettings(){data.user=$("#set-name").value||"Professora";save();$("#user-name").textContent=data.user;$("#avatar").textContent=data.user[0].toUpperCase();toast("Perfil atualizado")}
function photoPreview(input){if(input.files[0]){const r=new FileReader();r.onload=()=>{localStorage.setItem("pe_photo",r.result);toast("Foto carregada neste dispositivo")};r.readAsDataURL(input.files[0])}}
function toggleTheme(){data.theme=data.theme==="dark"?"light":"dark";save();document.body.classList.toggle("dark",data.theme==="dark")}
function createAccount(){const n=$("#signup-name").value,e=$("#signup-email").value,p=$("#signup-password").value;if(!n||!e||p.length<4){$("#signup-msg").textContent="Preencha nome, e-mail e uma senha com pelo menos 4 caracteres.";return}data.user=n;save();enter(n)}
$$("[data-action]").forEach(b=>b.addEventListener("click",()=>{const a=b.dataset.action;if(a==="start")start();if(a==="login")login();if(a==="signup")show("signup");if(a==="create-account")createAccount();if(a==="do-login")enter($("#email").value.split("@")[0]||"Professora");if(a==="google")enter("Professora Google");if(a==="demo")enter("Professora (demonstração)");if(a==="logout")login();if(a==="close-pix")$("#pix-modal").classList.add("hidden");if(a==="copy-pix")copyText(PIX);if(a==="menu")$(".sidebar").classList.toggle("open")}));
$$(".nav").forEach(n=>n.addEventListener("click",()=>{render(n.dataset.page);$(".sidebar").classList.remove("open");if(n.dataset.page==="calendar")setTimeout(drawEvents,0);if(n.dataset.page==="attendance")setTimeout(renderAttendance,0)}));
if(data.theme==="dark")document.body.classList.add("dark");
if(data.user){$("#user-name").textContent=data.user;$("#avatar").textContent=data.user[0].toUpperCase()}
show("landing");
