import { initializeApp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, updateProfile, sendPasswordResetEmail, GoogleAuthProvider, signInWithPopup, signOut } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import { getFirestore, doc, getDoc, setDoc, addDoc, collection, query, where, getDocs, deleteDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyCAoPpo30vk_aWjLRJPm1D55U10r25hr00",authDomain:"planejaeducaaaa.firebaseapp.com",projectId:"planejaeducaaaa",storageBucket:"planejaeducaaaa.firebasestorage.app",messagingSenderId:"619532705806",appId:"1:619532705806:web:dcb28fc66b8675298e1c5f",measurementId:"G-FJFKHN7W8J"};
const ADMIN_UID="BDmAQWzHytWVucAsuy4JiCOlIgB2";
const GRADES=["Educação Infantil","Pré I","Pré II","1º ano","2º ano","3º ano","4º ano","5º ano"];
const SUBJECTS=["Português","Matemática","Ciências","História","Geografia","Ensino Religioso","Arte","Educação Física","Projetos interdisciplinares"];
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
const $=id=>document.getElementById(id);
const toast=(msg,error=false)=>{const el=document.createElement("div");el.className="toast"+(error?" error":"");el.textContent=msg;$("toast").appendChild(el);setTimeout(()=>el.remove(),5000)};
const views={login:$('loginView'),dash:$('dashboardView'),new:$('newPlanView'),admin:$('adminView')};
function show(view){Object.values(views).forEach(v=>v.classList.add('hidden'));view.classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function go(hash){if(hash==='#novo-plano'){show(views.new);setPlanDate()}else if(hash==='#admin'){openAdminPage()}else{show(views.dash);loadPlans()}}
function setPlanDate(){$('pDate').value=new Date().toISOString().slice(0,10)}
document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('loginForm').classList.toggle('hidden',b.dataset.tab!=='login');$('registerForm').classList.toggle('hidden',b.dataset.tab!=='register')}));

async function isAdmin(user){if(user?.uid===ADMIN_UID)return true;try{const s=await getDoc(doc(db,'admin',user.uid));return s.exists()&&s.data().role==='admin'}catch(e){console.error(e);toast('Não foi possível consultar sua permissão administrativa. '+e.message,true);return false}}
async function getTeacherProfile(uid){try{const s=await getDoc(doc(db,'professores',uid));return s.exists()?s.data():null}catch(e){console.error(e);return null}}
async function enterUser(user){$('userLabel').textContent=user.displayName||user.email||'Usuário';$('logoutBtn').classList.remove('hidden');const admin=await isAdmin(user);$('adminBtn').classList.toggle('hidden',!admin);$('welcomeName').textContent=(user.displayName||user.email||'professora').split(' ')[0];await applyTeacherSettings(user);show(views.dash);loadPlans()}
onAuthStateChanged(auth,user=>{if(user)enterUser(user);else{$('logoutBtn').classList.add('hidden');$('adminBtn').classList.add('hidden');show(views.login)}});

$('loginBtn').onclick=async()=>{const email=$('email').value.trim(),pass=$('password').value;if(!email||!pass)return toast('Preencha e-mail e senha.',true);try{const r=await signInWithEmailAndPassword(auth,email,pass);await enterUser(r.user)}catch(e){console.error(e);toast('Não foi possível entrar: '+friendly(e),true)}};
$('registerBtn').onclick=async()=>{const name=$('regName').value.trim(),email=$('regEmail').value.trim(),p=$('regPassword').value,p2=$('regPassword2').value;if(!name||!email||p.length<6||p!==p2)return toast('Confira nome, e-mail e senhas.',true);try{const r=await createUserWithEmailAndPassword(auth,email,p);await updateProfile(r.user,{displayName:name});await setDoc(doc(db,'professores',r.user.uid),{uid:r.user.uid,nome:name,email,criadoEm:serverTimestamp(),ativo:true,turmas:[],disciplinas:[],escola:'',modalidade:'Regular',cabecalhoTipo:'',cabecalhoTexto:'',acessoGratuito:false},{merge:true});toast('Conta criada com sucesso!');await enterUser(r.user)}catch(e){console.error(e);toast('Não foi possível criar a conta: '+friendly(e),true)}};
$('forgot').onclick=async()=>{const email=$('email').value.trim();if(!email)return toast('Digite seu e-mail primeiro.',true);try{await sendPasswordResetEmail(auth,email);toast('Link de redefinição enviado para seu e-mail.')}catch(e){toast('Não foi possível enviar: '+friendly(e),true)}};
$('googleBtn').onclick=async()=>{try{const r=await signInWithPopup(auth,new GoogleAuthProvider());if(!await getDoc(doc(db,'professores',r.user.uid)).then(s=>s.exists()))await setDoc(doc(db,'professores',r.user.uid),{uid:r.user.uid,nome:r.user.displayName||'',email:r.user.email||'',criadoEm:serverTimestamp(),ativo:true,turmas:[],disciplinas:[],escola:'',modalidade:'Regular',cabecalhoTipo:'',cabecalhoTexto:'',acessoGratuito:false},{merge:true});await enterUser(r.user)}catch(e){toast('Login com Google não concluído: '+friendly(e),true)}};
$('logoutBtn').onclick=()=>signOut(auth);
$('demoBtn').onclick=()=>{toast('Modo demonstração: os planos criados aqui NÃO são salvos.');show(views.new);setPlanDate();$('demoMode').value='true';document.querySelectorAll('#newPlanView input,#newPlanView textarea').forEach(x=>x.value='')};

async function applyTeacherSettings(user){const p=await getTeacherProfile(user.uid);const allowedGrades=(p?.turmas||[]).filter(x=>GRADES.includes(x));const allowedSubjects=(p?.disciplinas||[]).filter(x=>SUBJECTS.includes(x));fillSelect($('pGrade'),allowedGrades.length?allowedGrades:GRADES);fillSelect($('pSubject'),allowedSubjects.length?allowedSubjects:SUBJECTS);if(p){$('pSchool').value=p.escola||'';$('pMode').value=p.modalidade||'Regular';$('teacherHeaderNote').textContent=p.cabecalhoTexto||'';}}
function fillSelect(el,items){el.innerHTML=items.map(x=>`<option>${esc(x)}</option>`).join('')}

let currentPlans=[];
async function loadPlans(){const user=auth.currentUser;if(!user)return;$('plansGrid').innerHTML='<div class="empty">Carregando seus planos...</div>';try{const q=query(collection(db,'planos'),where('uid','==',user.uid));const snap=await getDocs(q);currentPlans=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>{const aa=a.criadoEm?.seconds||0,bb=b.criadoEm?.seconds||0;return bb-aa});renderPlans(currentPlans)}catch(e){console.error(e);$('plansGrid').innerHTML='<div class="empty"><strong>Não foi possível carregar seus planos.</strong><br><small>'+esc(e.message)+'</small></div>'}}
function renderPlans(plans){$('totalPlans').textContent=plans.length;const now=new Date();$('monthPlans').textContent=plans.filter(p=>{const d=p.criadoEm?.toDate?.();return d&&d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}).length;const term=$('searchPlans').value.toLowerCase();const filtered=plans.filter(p=>(p.titulo+' '+p.turma+' '+p.disciplina).toLowerCase().includes(term));if(!filtered.length){$('plansGrid').innerHTML='<div class="empty"><strong>Você ainda não tem planos salvos.</strong><br>Crie seu primeiro planejamento usando “Novo plano de aula”.</div>';return}$('plansGrid').innerHTML=filtered.map(p=>`<article class="plan-card"><span class="tag">${esc(p.disciplina||'Planejamento')}</span><h3>${esc(p.titulo||'Sem título')}</h3><p>${esc(p.turma||'')} · ${esc(p.data||'')}</p><p>${esc(p.escola||'')}</p><div class="plan-actions"><button class="mini-btn" data-open="${p.id}">Visualizar</button><button class="mini-btn" data-del="${p.id}">Excluir</button></div></article>`).join('');document.querySelectorAll('[data-del]').forEach(b=>b.onclick=()=>deletePlan(b.dataset.del));document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openPlan(plans.find(p=>p.id===b.dataset.open)))}
$('searchPlans').addEventListener('input',()=>renderPlans(currentPlans));
async function deletePlan(id){if(!confirm('Excluir este plano?'))return;try{await deleteDoc(doc(db,'planos',id));toast('Plano excluído.');loadPlans()}catch(e){toast('Não foi possível excluir: '+e.message,true)}}
function openPlan(p){if(!p)return;const w=window.open('','_blank');w.document.write(`<html><head><title>${esc(p.titulo)}</title><style>body{font:16px Arial;color:#18213c;max-width:850px;margin:50px auto;line-height:1.7}h1{font-size:30px}h2{font-size:16px;color:#5b4be7;border-bottom:1px solid #ddd;padding-bottom:7px;margin-top:28px}.meta{background:#f4f5fb;padding:16px;border-radius:10px}</style></head><body><h1>${esc(p.titulo)}</h1><div class="meta"><b>${esc(p.escola||'')}</b><br>${esc(p.turma||'')} · ${esc(p.disciplina||'')} · ${esc(p.data||'')}</div>${section('Objetivos',p.objetivos)}${section('Habilidades / BNCC',p.bncc)}${section('Conteúdo',p.conteudo)}${section('Metodologia',p.metodologia)}${section('Recursos',p.recursos)}${section('Avaliação',p.avaliacao)}${section('Observações',p.observacoes)}</body></html>`);w.document.close()}
function section(t,v){return `<h2>${t}</h2><p>${esc(v||'—').replace(/\n/g,'<br>')}</p>`}

$('savePlanBtn').onclick=async()=>{const user=auth.currentUser;if(!user)return toast('Faça login para salvar.',true);if($('demoMode').value==='true')return toast('Modo demonstração: este plano não pode ser salvo.',true);const title=$('pTitle').value.trim();if(!title)return toast('Informe o título do plano.',true);const data={uid:user.uid,titulo:title,data:$('pDate').value,turma:$('pGrade').value,disciplina:$('pSubject').value,escola:$('pSchool').value.trim(),modalidade:$('pMode').value,objetivos:$('pObjectives').value,bncc:$('pBncc').value,conteudo:$('pContent').value,metodologia:$('pMethod').value,recursos:$('pResources').value,avaliacao:$('pAssessment').value,observacoes:$('pNotes').value,criadoEm:serverTimestamp()};try{await addDoc(collection(db,'planos'),data);toast('Plano salvo no seu espaço!');$('demoMode').value='false';show(views.dash);loadPlans()}catch(e){console.error(e);toast('Não foi possível salvar. '+e.message,true)}};

async function openAdminPage(){const u=auth.currentUser;if(!u)return;if(!(await isAdmin(u)))return toast('Acesso administrativo negado.',true);show(views.admin);loadAdminData()}
$('adminBtn').onclick=()=>openAdminPage();
$('adminBackBtn').onclick=()=>{show(views.dash);loadPlans()};
$('adminRefresh').onclick=()=>loadAdminData();
let teachers=[];
async function loadAdminData(){if(auth.currentUser?.uid!==ADMIN_UID&&!await isAdmin(auth.currentUser))return;$('adminUidLabel').textContent=auth.currentUser.uid;$('adminTeachersGrid').innerHTML='<div class="empty">Carregando professoras...</div>';try{const snap=await getDocs(collection(db,'professores'));teachers=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.nome||'').localeCompare(b.nome||''));$('adminTeacherCount').textContent=teachers.length;renderTeacherCards(teachers)}catch(e){console.error(e);$('adminTeachersGrid').innerHTML='<div class="empty"><strong>Erro ao carregar professoras.</strong><br><small>'+esc(e.message)+'</small></div>';toast('Erro no Firestore: '+e.message,true)}}
function renderTeacherCards(list){if(!list.length){$('adminTeachersGrid').innerHTML='<div class="empty">Nenhuma professora cadastrada ainda.</div>';return}$('adminTeachersGrid').innerHTML=list.map(t=>`<article class="teacher-card"><div class="teacher-top"><div class="avatar">${esc((t.nome||t.email||'?').slice(0,1).toUpperCase())}</div><div><h3>${esc(t.nome||'Sem nome')}</h3><p>${esc(t.email||'')}</p></div><span class="status ${t.ativo===false?'off':'on'}">${t.ativo===false?'Inativa':'Ativa'}</span></div><div class="teacher-tags">${(t.turmas||[]).map(x=>`<span>${esc(x)}</span>`).join('')||'<span>Nenhuma turma</span>'}${(t.disciplinas||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="teacher-meta"><b>${esc(t.escola||'Escola não definida')}</b><span>${esc(t.modalidade||'Regular')} · ${t.acessoGratuito?'Acesso liberado':'Acesso padrão'}</span></div><button class="btn btn-outline wide" data-edit-teacher="${t.id}">Administrar professora</button></article>`).join('');document.querySelectorAll('[data-edit-teacher]').forEach(b=>b.onclick=()=>openTeacherEditor(teachers.find(t=>t.id===b.dataset.editTeacher)))}
$('teacherSearch').addEventListener('input',()=>{const q=$('teacherSearch').value.toLowerCase();renderTeacherCards(teachers.filter(t=>(t.nome+' '+t.email+' '+(t.escola||'')).toLowerCase().includes(q)))});
function openTeacherEditor(t){if(!t)return;$('teacherEditUid').value=t.uid||t.id;$('teacherEditName').value=t.nome||'';$('teacherEditEmail').value=t.email||'';$('teacherEditSchool').value=t.escola||'';$('teacherEditMode').value=t.modalidade||'Regular';$('teacherEditHeaderType').value=t.cabecalhoTipo||'';$('teacherEditHeader').value=HEADER_LABELS[t.cabecalhoTipo]||t.cabecalhoTexto||'';$('teacherEditFree').checked=!!t.acessoGratuito;$('teacherEditActive').checked=t.ativo!==false;document.querySelectorAll('.assign-grade').forEach(c=>c.checked=(t.turmas||[]).includes(c.value));document.querySelectorAll('.assign-subject').forEach(c=>c.checked=(t.disciplinas||[]).includes(c.value));$('teacherModal').classList.remove('hidden')}
$('closeTeacherModal').onclick=()=>$('teacherModal').classList.add('hidden');
document.addEventListener('change',e=>{if(e.target.id==='teacherEditHeaderType'){const v=e.target.value;$('teacherEditHeader').value=HEADER_LABELS[v]||'';}});

$('saveTeacherBtn').onclick=async()=>{const uid=$('teacherEditUid').value.trim();if(!uid)return;const turmas=[...document.querySelectorAll('.assign-grade:checked')].map(c=>c.value);const disciplinas=[...document.querySelectorAll('.assign-subject:checked')].map(c=>c.value);const payload={nome:$('teacherEditName').value.trim(),email:$('teacherEditEmail').value.trim(),escola:$('teacherEditSchool').value.trim(),modalidade:$('teacherEditMode').value,cabecalhoTipo:$('teacherEditHeaderType').value,cabecalhoTexto:HEADER_LABELS[$('teacherEditHeaderType').value]||$('teacherEditHeader').value.trim(),acessoGratuito:$('teacherEditFree').checked,ativo:$('teacherEditActive').checked,turmas,disciplinas,uid,atualizadoEm:serverTimestamp()};try{await setDoc(doc(db,'professores',uid),payload,{merge:true});toast('Dados da professora atualizados.');$('teacherModal').classList.add('hidden');loadAdminData()}catch(e){console.error(e);toast('Não foi possível salvar: '+e.message,true)}};
$('closeAdminTeacherFromView').onclick=()=>{$('teacherModal').classList.add('hidden')};

function friendly(e){return ({'auth/invalid-credential':'E-mail ou senha incorretos.','auth/invalid-email':'E-mail inválido.','auth/user-not-found':'Usuário não encontrado.','auth/wrong-password':'Senha incorreta.','auth/email-already-in-use':'Este e-mail já possui uma conta.','auth/too-many-requests':'Muitas tentativas. Aguarde alguns minutos e tente novamente.','auth/operation-not-allowed':'O método de login ainda não está habilitado no Firebase.'})[e.code]||e.message||'Erro desconhecido.'}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
